
dailymotion:
  username:       <%= ENV['DAILYMOTION_USERNAME'] %>
  password:       <%= ENV['DAILYMOTION_PASSWORD'] %>
  client_id:      <%= ENV['DAILYMOTION_CLIENT_ID'] %>
  client_secret:  <%= ENV['DAILYMOTION_CLIENT_SECRET'] %>
