defaults: &defaults
  host: 127.0.0.1
  port: 6379

development:
  <<: *defaults

test:
  <<: *defaults

# set these environment variables on your prod server
production:
  url: <%= ENV['REDISTOGO_URL'] %>
